-- RUN THIS IN YOUR SUPABASE SQL EDITOR --

-- 1. Profiles table (linked to Auth)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE,
  username TEXT UNIQUE,
  full_name TEXT,
  avatar_url TEXT,
  bio TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  PRIMARY KEY (id)
);

-- 2. Posts table
CREATE TABLE posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles (id) ON DELETE CASCADE,
  content_url TEXT NOT NULL,
  caption TEXT,
  type TEXT DEFAULT 'image', -- 'image' or 'video'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Likes table
CREATE TABLE likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles (id) ON DELETE CASCADE,
  post_id BIGINT REFERENCES posts (id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, post_id)
);

-- 4. Comments table
CREATE TABLE comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles (id) ON DELETE CASCADE,
  post_id BIGINT REFERENCES posts (id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Messages table
CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id UUID REFERENCES profiles (id) ON DELETE CASCADE,
  receiver_id UUID REFERENCES profiles (id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- 7. Basic Policies
CREATE POLICY "Public profiles are viewable by everyone." ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can handle own profile." ON profiles FOR ALL USING (auth.uid() = id);

CREATE POLICY "Posts are viewable by everyone." ON posts FOR SELECT USING (true);
CREATE POLICY "Users can insert posts." ON posts FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Likes/Comments are viewable by everyone." ON likes FOR SELECT USING (true);
CREATE POLICY "Likes/Comments can be added by auth users." ON likes FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Comments viewable by everyone." ON comments FOR SELECT USING (true);
CREATE POLICY "Comments can be added by auth users." ON comments FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Messages viewable by sender/receiver." ON messages FOR SELECT USING (auth.uid() = sender_id OR auth.uid() = receiver_id);
CREATE POLICY "Messages can be sent by auth users." ON messages FOR INSERT WITH CHECK (auth.uid() = sender_id);

-- 8. Storage Setup (Create bucket 'posts_content' manually in UI, set to PUBLIC)
-- After creating the bucket, run these policies:

CREATE POLICY "Public Read Access" ON storage.objects FOR SELECT USING (bucket_id = 'posts_content');
CREATE POLICY "Authenticated Upload" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'posts_content');
CREATE POLICY "Delete own files" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'posts_content' AND (storage.foldername(name))[1] = auth.uid()::text);
